### ISSUE TITLE
PHP code detected as HTML, if indented with tabs

### ISSUE THREAD

**Issue by blueyed** [tomtom/tcomment_vim#123]
Given the following file, where the `return` is indented with a single tab, `gcc` treats it as html:

    <?php
    	return;

I am using `g:tcommentGuessFileType_php = "html"`.
The syntax region is `phpRegion`.

When using spaced for indentation, it gets commented as PHP correctly.

I am using `expandtab`, in case that's relevant and is involved during the detection.

**Comment by hahiserw** [comment]
Hi, I think I have a similiar problem. Here's how to reproduce it.
```php
<?php

	switch ($whatever) {
	case 'lol':
		die();
		break;
	default:
		die('omg');
	}

// try commenting out 5th or 6th line
```

**Comment by blueyed** [comment]
I can still reproduce my issue: make sure there's a literal tab before `return;`.

The syntax is `phpStatement phpRegion` for me there, too.

After `gcc` it becomes `<!-- return; -->`, and with `gcc` again `// <!-- return; -->` (which then toggles).

**Comment by blueyed** [comment]
It happens also with the example from @hahiserw on line 5, with a literal tab (`<C-v><Tab`) before it.

Might be some regexp that looks for spaces, but not whitespace in general?!

**Comment by tomtom** [comment]
Thanks for pointing out the tab character.
