### ISSUE TITLE
tcomment inserts whitespaces when commenting

### ISSUE THREAD

**Issue by chilicuil** [tomtom/tcomment_vim#127]
Hi,

First of all thanks for the great work on this plugin, I've been using tcomment for a couple of weeks and the only thing than bugs me is than when I comment lines it adds automatically a whitespace at the beginning of them.

I have the following map declared:

    map <leader>c<space>       <Plug>TComment_<c-_><c-_>

And after pressing `<leader>c<space>`  on lines such as the following:

    noremap <m-home> gg

I get

    "_noremap <m-home> gg

What I want is:

    "noremap <m-home> gg

Without the whitespace, I looked quickly at the documentation and wasn't able to find an option to control such behavior. Thoughts?

Cheers.

**Comment by angelic-sedition** [comment]
I think the whitespace is nice (and pretty standard for commenting plugins). To change it, you can put `call tcomment#DefineType('vim', '"%s' )` in your ~/.vimrc if you want though. It may be a pain to do that for every filetype, but it should work.

**Comment by chilicuil** [comment]
Oh, so there is a way, cool, then I'm closing this issue. Thanks!

**Comment by tomtom** [comment]
An easier solution would be to add

    let g:tcommentOptions = {'whitespace': 'no'}

to your vimrc file. HTH
