### ISSUE TITLE
Command to Comment Only if Currently Uncommented

### ISSUE THREAD

**Issue by angelic-sedition** [tomtom/tcomment_vim#128]
This would work basically like the toggle (`:TComment`) except that if the line was commented, it would do nothing. I wouldn't often use this manually. I've used TComment in macros and mappings before where using `:TComment` resulted in a line or lines being uncommented that I still wanted commented and using the explicit comment command resulted in unwanted extra comment characters.

Another example of where this would be useful is for commenting a section where some lines were already commented out but nested commenting wasn't wanted. Usually I like this (having already existing comments commented again so they return to normal if uncommenting), but occasionally I don't want this behaviour.

**Comment by tomtom** [comment]
You should now be able to use `:TComment mode=K`to achieve what you want.

**Comment by angelic-sedition** [comment]
I that the literal command? `:TComment mode=K<cr>` is behaving the same for me as the toggle 
no mode given).

**Comment by angelic-sedition** [comment]
Awesome, thanks!
