### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by wikimatze** [tomtom/tcomment_vim#129]
I'm using a plugin manager for vim called [vim-plug](https://github.com/junegunn/vim-plug) and I don't always want to grab from master to track the changes a plugin takes.

Bests from Berlin

Matthias

**Comment by tomtom** [comment]
> I'm using a plugin manager for vim called vim-plug 
> <https://github.com/junegunn/vim-plug> and I don't always want to grab 
> from master to track the changes a plugin takes.
>
As you could easily find out yourself, releases are tagged:
https://github.com/tomtom/tcomment_vim/releases
https://github.com/tomtom/tcomment_vim/tags

Maybe you mean something else like a release branch or something?

**Comment by wikimatze** [comment]
Yeah, I'm exactly meaning this. The last release is 3.04 from 10th of September 2014 and I thought it would be nice to have a fresh release.

**Comment by wikimatze** [comment]
Thanks for creating a new one.
