### ISSUE TITLE
How can I make gc behave like gcc outside of visual mode?

### ISSUE THREAD

**Issue by mcandre** [tomtom/tcomment_vim#130]
I would like `gc` to behave like `gcc` when outside of visual mode. What can I drop into my `$HOME/.vimrc` to accomplish this?

**Comment by tomtom** [comment]
gc is an operator in normal mode. Please describe in detail what you're trying to accomplish.

**Comment by mcandre** [comment]
As a former Emacs user, I enjoyed using the same hotkey for toggling commenting.

When I select text, evil-nerd-comment would toggle commenting for the selected text. When no text was selected, evil-nerd-comment would toggle commenting for the current line.

I'd love for tcomment to provide a `g*`, `g;`, etc. key combination out of the box with this behavior, but I'd also be satisfied with an example configuration snippet that I can drop in my .vimrc.

**Comment by tomtom** [comment]
I'm sorry but I don't understand what you want to achieve that tcomment doesn't provide. <c-_> and gc maps work as toggles as you described above. That evil-nerd-comment uses g*, g; maps isn't even marginally interesting. As a former emacs user, you might prefer the <c-_> maps or read up on vim operators.

**Comment by mcandre** [comment]
I'll try to rephrase.

While tcomment's `gc` and `gcc` commands are useful, I would prefer a single command that behaves as `gc` in visual mode, and `gcc` in normal mode.

**Comment by tomtom** [comment]
> While tcomment's |gc| and |gcc| commands are useful, I would prefer a 
> single command that behaves as |gc| in visual mode, and |gcc| in 
> normal mode. 
What's wrong with <c-_>?

There is a reason that gc in visual mode works immediatly on the visual 
area while the normap mode map gc waits for a movement.

One could argue, as you seem to do, that the visual mode map should be 
gcc (even though this would be one key more to type). I'd counter this 
isn't consistent with other vim visual/operator maps.

**Comment by mcandre** [comment]
I respect how `gc` and `gcc` currently work. I would like a third hotkey that acts as the appropriate `gc` or `gcc` for whichever mode I'm in.

**Comment by tomtom** [comment]
As said above, there is also `<c-_>`, which also works for selection and insert mode. Users can also easily use the <Plug>... maps provided in plugin/tcomment.vim to create their own maps.

**Comment by mcandre** [comment]
`<c-_>` does not appear to do anything on my machine.

**Comment by tomtom** [comment]
> |<c-_>| does not appear to do anything on my machine.
>
It's a prefix. From :help tcomment-maps

     <c-_><c-_>   :: :TComment
     <c-_>b       :: :TCommentBlock
                     In insert mode, the cursor will be positioned inside
                     the comment. In normal mode, the cursor will stay
                     put.
