### ISSUE TITLE
gc: Don't comment the line after my selected text

### ISSUE THREAD

**Issue by mcandre** [tomtom/tcomment_vim#131]
`gc` keeps commenting out the empty line after my selected text.

I'm using `$` to go to the end of the line in visual mode, in case that matters.

**Comment by tomtom** [comment]
It would be nice if you described precisely what you're doing ... step by step. What's the value of &selection? Which version of VIM do you run under which OS?

**Comment by mcandre** [comment]
Original buffer:

```
a

bcde

fghi
```

Approximate steps to reproduce:

```
gg
v
j
j
$
gc
```

The result is that tcomment comments out the empty line between `bcde` and `fghi`, even though the visual selection is only to the end of `bcde`.

**Comment by tomtom** [comment]
Which version of tcomment do you use?I tested your example with &selection set to inclusive and exclusive. The fourth line wasn't commented out. You still didn't tell me what's the value of 'selection'.

Anyway, you might want to use gggc2j instead of virtual regions (see :help operator).

**Comment by mcandre** [comment]
I'm using git HEAD of tcomment via Vundle.

**Comment by tomtom** [comment]
Did you test it with vanilla vim?

   vim -u minirc.vim

with minirc.vim:

     set nocp
     filetype plugin indent on
     syntax on

     let s:ps = ['tcomment']
     for s:p in s:ps
         exec 'set rtp+=~/.vim/bundle/'. s:p
     endfor
     unlet! s:p s:ps

If you don't provide more details, I won't be able to help you.

**Comment by mcandre** [comment]
For context, my .vimrc is:

https://github.com/mcandre/dotfiles/blob/master/.vimrc

**Comment by tomtom** [comment]
Please report back when you verified that the problem persists with vanilla vim.
