### ISSUE TITLE
How to set filetype

### ISSUE THREAD

**Issue by delijati** [tomtom/tcomment_vim#138]
Hi my current is ``filetype=jinja`` for ``html`` and but somehow i get ``/* */`` and not as expected ``<!-- -->``.

**Comment by tomtom** [comment]
Previous users used fileype=htmljinja. Isn't `{# %s #}` the commentstring for that?

**Comment by delijati** [comment]
I'm using this plugin https://github.com/Glench/Vim-Jinja2-Syntax.git and that plugin is setting the filetype to jinja. As a solution maybe i can fore tcomment to interpret jinja as html?

**Comment by delijati** [comment]
Oh cool thanks.
