### ISSUE TITLE
let g:tcommentMapLeaderOp1 = <Leader>c Not work

### ISSUE THREAD

**Issue by jinleileiking** [tomtom/tcomment_vim#142]
` let g:tcommentMapLeaderOp1 = <Leader>c`

not work.

Cannot use leader.

**Comment by tomtom** [comment]
> |let g:tcommentMapLeaderOp1 = <Leader>c|
>
|1. You should use ||g:tcommentMapLeaderOp2 for maps with <Leader>

2. Just to verify: When you set
|
|    let g:tcommentMapLeaderOp2 = '<Leader>c'

__before__ loading the plugin (e.g. in vimrc) and after you verified the 
plugin works by typing, e.g., gcc, then, e.g., <Leader>c_ doesn't toggle 
the comment of the current line?
|

**Comment by tomtom** [comment]
Note: The g:tcommentMapLeader2 maps are not defined for insert mode.

**Comment by tomtom** [comment]
Just to clarify the point on |g:tcommentMapLeaderOp1: You should set 
||g:tcommentMapLeaderOp1 to a map that can be typed in insert mode with 
no problems -- most likely some <c-KEY> combination.
|

**Comment by jinleileiking** [comment]
Seems not work. I use default maps instead...
