### ISSUE TITLE
Sometimes PHP comments using HTML comment syntax

### ISSUE THREAD

**Issue by codeinabox** [tomtom/tcomment_vim#144]
I've noticed lately when I am commenting code in a PHP class it is using HTML comment syntax, for example

```php
        $callingUser = $this->anyUser();
        $callingShop = $this->anyShop();
```
On commenting becomes

```php
        <!-- $callingUser = $this&#45;>anyUser(); -->
        <!-- $callingShop = $this&#45;>anyShop(); -->
```

**Comment by tomtom** [comment]
If the above commit doesn't solve the problem, please post more details (full working example etc.).

**Comment by codeinabox** [comment]
Issue is still occurring, created full example at #145
