### ISSUE TITLE
Add support for robot files

### ISSUE THREAD

**Issue by aswna** [tomtom/tcomment_vim#147]
Hi Tom!
Could you, please, add support for Robot files (filetype is robot)?
[Ignored data](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id419) in Robot files: *"All characters following the hash character (#), when it is the first character of a cell. This means that hash marks can be used to enter comments in the test data."*
I think the best would be to put the # characters at the first column of the lines.

Thanks!

**Comment by aswna** [comment]
I have added the following in autoload/tcomment.vim (before the "robots" definition):
call tcomment#DefineType('robot',            {'col': 1, 'commentstring': '# %s'})

It seems that the "col" setting does not work, tcomment always puts the comment sign (#) indented.
Any ideas?

**Comment by aswna** [comment]
If I uncomment this line (approx. line 810):
let cbeg = get(s:cdef, 'col', cbeg)
then it works.
What is the catch?

**Comment by tomtom** [comment]
The line was disabled in commit aaf75b948f95e79bd2ff78f17269a9c933603dfe, probably due to a bad interaction with k mode.

**Comment by aswna** [comment]
Thanks! It works for me.
