### ISSUE TITLE
Uncomment makes indentation off by one space

### ISSUE THREAD

**Issue by myriasofo** [tomtom/tcomment_vim#152]
**Clarification of the problem:**
* Javascript. 
* 4 space indentation.
* I try to uncomment (ie. `<Plug>TComment_Uncomment`).
* Line has spaces between comment chars (//) and code
* Code is now shifted over one space left. So 3 spaces instead of 4 spaces.

EXAMPLE - Starting position:
```
example0
    //example1
    //    example2
        example3
    example4
        example5
        example6
```
Then I uncomment:
```
example0
    example1
       example2
        example3
    example4
        example5
        example6
```

Look at `example2` - it is off by one space. While `example1` is still inline.
Here are more details:
* No problem if whitespace is set to 'yes'. (Note: I feel the problem has to do with this)
* Occurs in .js files as well as with javascript in .html between `<script>` tags.
* Does NOT happen with vimscript or python
* Using Vim 7.4, Windows 7.

**Comment by tomtom** [comment]
> No problem if whitespace is set to 'yes'. (Note: I feel the problem 
> has to do with this)

tcomment assumes the comment prefix is "// " (incl whitespace). This 
will be removed too. tcomment could try to guess whether the text was 
commented with "// " or just "//" but this is IMHO overly complex & I 
think the better procedure would be to run `=` on uncommented text. I 
guess I could add an option to do this automatically on uncomments.

**Comment by myriasofo** [comment]
Got it, your explanation makes a lot of sense. The thing is - I just checked in python, and strangely, it works perfectly there. As normal, with whitespace:yes, a line with 4 spaces gets an added space and has it taken away  (ie. '4321code' becomes '#**5**4321code'. Uncomment brings it back to '4321code'.). 

However, with whitespace:no, a line with 4 spaces does what I want: '4321code' becomes '#4321code' and uncomments back to '4321code'. That is, python does this behavior right, but javascript doesn't. Why is that? (Vimscript also works. It seems that javascript is the exception)

**Comment by tomtom** [comment]
Your python example is wrong. It should be:

    example0
        #example1
        #    example2
            example3

Same problem as above.

To some extent tcomment is able to cope with inconsistent comment styles. I.e. "#foo" and "# foo" will be become "foo" if whitspace is `both` or `left`. The problem with your example is that multiple blanks follow the comment prefix and tcomment will assume that "#    foo" was commented with a single whitespace character after the prefix.
