### ISSUE TITLE
how to add new comment for new file type?

### ISSUE THREAD

**Issue by cyboflash** [tomtom/tcomment_vim#153]
how do i add new comment for a new file type? 

i'm working with `tblgen` files but the plugin use correct comment character for them. how do i make it use a correct one?

**Comment by tomtom** [comment]
> i'm working with |tblgen| files but the plugin use correct comment 
> character for them. how do i make it use a correct one? 

Users should use the `tcomment#DefineType` function:

call tcomment#DefineType('tblgen', tcomment#GetLineC('// %s'))
call tcomment#DefineType('tblgen_block',        g:tcommentBlockC   )
call tcomment#DefineType('tblgen_inline',       g:tcommentInlineC  )

If tblgen comments are the same as c++, you could also use:

let g:tcomment#filetype_map['tblgen'] = 'cpp'

Does this help?

**Comment by cyboflash** [comment]
After executing `let g:tcomment#filetype_map['tblgen'] = 'cpp'`, I got the following response:
`E121: Undefined variable: g:tcomment#filetype_map`

**Comment by tomtom** [comment]
> After executing |let g:tcomment#filetype_map['tblgen'] = 'cpp'|, I got 
> the following response:
> |E121: Undefined variable: g:tcomment#filetype_map|
>
The version on github now includes his mapping.
