### ISSUE TITLE
Toggle block comment

### ISSUE THREAD

**Issue by ggVGc** [tomtom/tcomment_vim#154]
Is there a way to toggle a block comment, by putting the cursor somewhere inside the commented block? Preferably there would be a text object such as "Inner block comment" that could be used with `gc` or other commands taking motions.

**Comment by tomtom** [comment]
> Is there a way to toggle a block comment, by putting the cursor 
> somewhere inside the commented block?
>
No.
>
> Preferably there would be a text object such as "Inner block comment" 
> that could be used with |gc| or other commands taking motions.
>
This doesn't exist yet. There is a text object for inline comments but 
this doesn't work properly. I currently don't have the time to work on this.

IMHO you should use block comments only for documentation.

**Comment by tomtom** [comment]
There are plugins that define text objects based on the syntax group, e.g. <https://github.com/kana/vim-textobj-syntax>. I haven't tried it myself, but i figured if I would implement the feature you're asking for I'd take that approach too and create a map to select the text in the current syntax group.

**Comment by tomtom** [comment]
With vim-textobj-syntax, you could do: `viy<c-b>`.
