### ISSUE TITLE
comment folds

### ISSUE THREAD

**Issue by Konfekt** [tomtom/tcomment_vim#158]
If the cursor is on a fold, then `dd` deletes the fold (and, likewise, `yy` yanks and `cc` changes it).
How about, if the cursor is on a fold, then `gcc` (un)comments the fold ?

The following map achieves that
```vim
nnoremap <expr> gcc (foldclosed('.') == -1 ? ':TComment<CR>' : ':' . foldclosed('.') . ',' . foldclosedend('.') . 'TComment<CR>' ) . ':silent! call repeat#set("gcc", v:count)<cr>'
```

**Comment by tomtom** [comment]
I think the proper way would be to do `Vgc`

V ... visually select fold(s)
gc ... comment visual selection

The gcc map isn't well suited for this because it explicitly works on a single line.

You could also use some plugin that provides a text object for folds.
