### ISSUE TITLE
How to add a JSX file support?

### ISSUE THREAD

**Issue by tom31203120** [tomtom/tcomment_vim#159]

**Comment by tomtom** [comment]
Take a look at autoload/tcomment.vim and search for `call tcomment#DefineType(`.

JSX support was already added some time ago. Please make sure the filetype is set to jsx and tcomment was properly loaded.

**Comment by alextes** [comment]
Hm, not working for me @tomtom . Was working at some point. How do I go about debugging this. Currently neither filetype `javascript.jsx` or `typescript.tsx` seem to get JSX style comments. In the following:
```javascript.jsx
class MyClass extends React.Component {
  render() {
    return (
      <div />
    );
  }
}
```
Commenting the `<div />` line results in `//` being prepended.

Thanks for building this awesome plugin by the way! The [issue on vim-commentary](https://github.com/tpope/vim-commentary/issues/68) didn't look very promising.

**Comment by tomtom** [comment]
> class  MyClass  extends  React.Component  {
>    render() {
>      return  (
>        <div  />
          ^
          could you please place the cursor here and check what's the 
syntax group

The result of

          echom &ft synIDattr(synID(line("."), col("."), 1), "name")

would be useful.

**Comment by alextes** [comment]
`typescript.tsx tsxTag`

hm. I have a hunch `tcomment` stopped working when I switched from `leafgarland/typescript-vim` to `HerringtonDarkholme/yats.vim` 😅 .

**Comment by ApolloTang** [comment]
related to #186 ?

**Comment by alextes** [comment]
@ApolloTang A little bit, it's both a question of identification of syntax. However, it appears in your case tcomment is misidentifying jsx as xml, in this issue tcomment appears not to recognize the syntax at all and default to commenting with `//`.

**Comment by tomtom** [comment]
Does it help to set

    let g:tcomment#filetype#guess_typescript = 1

**Comment by tomtom** [comment]
If the problem still persists after the latest update, please see `:h tcomment-debug` or the hopefully helpful instructions at https://github.com/tomtom/tcomment_vim for how to collect the necessary data/logs (`:call tcomment#DebugInfo()`) that could help resolving this issue.

**Comment by tomtom** [comment]
Does the latest update make this work?

**Comment by alextes** [comment]
@tomtom it does 👌 . Unfortunately, it also breaks something that happened to be working. JSX can be pedantic.

Take the following:
```jsx
return ( // Works!
  <View style={styles.container}>
    <Separator variant="fullWidth" /> // Needs {/* */} works!
    <Spacer size="s" />
    <FlatList
      ref="listRef"
      data={results} // Needs // breaks!
      keyExtractor={item => item.id}
      renderItem={({ item, index }) => (
        <ListItem
          index={index}
          car={item}
          onPress={car => this.onPressItem(car)}
        />
      )}
      ItemSeparatorComponent={() => <Separator />}
      onRefresh={this.refreshCars}
      refreshing={refreshing}
    />
    {loading ? <Loader /> : null}
  </View>
);
```

The tricky part is that `javascript.jsx xmlAttrib` needs a different comment style depending on if it's on its own line. Not sure if this is still within scope for tcomment 😅.

**Comment by ApolloTang** [comment]
@alextes I got my issue resolved by using a different jxs syntax plugin (see my latest comment in #186)
