### ISSUE TITLE
tcommentOptions 'col' should be ignored for non-line comments?

### ISSUE THREAD

**Issue by agilmor** [tomtom/tcomment_vim#162]
Hi,

I need to have the line comments at the first column.
And when I set the `let g :tcommentOptions = {'col': 1}` it does the job, great! 

But then, if I want to comment, not a line, but a text object like an "inner word" (`gciw`), it doesn't work as before (as expected) anymore. The first comment string is also on the first column, not right before the "inner word" as it was without the `col=N` option.

Maybe it is the expected behaviiour and I just need more setup to have what I want, or maye what I want is just unsupported...?
But right now it seems an issue to me?

Thanks!

Albert

**Comment by agilmor** [comment]
Thanks a lot for so quick fix!
It worked like a charm!

But, is it possible that now (with this fix), when using line comment (```gcc```) it sometimes uses block-style instead of line-style comment?
I'm experiencing this in cpp code, it (sometimes) uses ```/* */``` instead of ```//```. 

But, as I said, the fix worked and now this issue is not anymore present, with col=1 I can comment a word correclty.

So, maybe I should create a new issue with more details of the line/block comments on cpp?

Thanks!

**Comment by tomtom** [comment]
> I'm experiencing this in cpp code, it (sometimes) uses |/* */| instead 
> of |//|. 
I couldn't reproduce the problem. Are you sure the filetype is cpp, not 
c? Could you please post some example code that triggers this problem?

**Comment by agilmor** [comment]
The filetype is ```cpp.doxygen```.
And you are right, if I set the filetype to just ```cpp``` then it always use line-style.

Probably the strange part is the kind of random behavior in ```cpp.doxygen```.
This is the orignal piece of code:
```
class MyClass
{
public:

    MyClass(const std::string& s) : _my_var(s)
    {}

    ~MyClass()
    {}

    const char* cstr()
    {
        return _error_msg.c_str();
    }

private:
   std::string _my_var;
};
```

And I get these mixed comment styles when commenting different lines;
```
class MyClass
{
public:

/*     MyClass(const std::string& s) : _my_var(s) */
    {}

//     ~MyClass()
    {}

/*     const char* cstr() */
    {
/*         return _error_msg.c_str(); */
    }

private:
//    std::string _my_var;
};
```

If I set the filetype to only ```cpp```, then I get the expected results:
```
class MyClass
{
public:

//     MyClass(const std::string& s) : _my_var(s)
    {}

//     ~MyClass()
    {}

//     const char* cstr()
    {
//         return _error_msg.c_str();
    }

private:
//    std::string _my_var;
};
```
Do you think that this can be fixed?
I add the doxygen filetype for nicer syntax highlight, but I will never re-comment or uncomment any doxygen documentation! ;-)

Thanks a lot!!

Albert
