### ISSUE TITLE
error while processing function

### ISSUE THREAD

**Issue by danielb2** [tomtom/tcomment_vim#167]
Since an update to a later version of tcomment, I'm getting the error below. 
```
Error detected while processing function TCommentOpFunc_gcc[3]..tcomment#OperatorLine[2]..tcomment#Ope
rator[53]..tcomment#Comment[53]..<SNR>166_GetCommentDefinition:
line    2:
E492: Not an editor command:     Tlibtrace 'tcomment', a:beg, a:end, a:comment_mode, ft
```

any ideas what this may be?

`NVIM v0.1.3-300-g3223801`

**Comment by tomtom** [comment]
> |E492: Not an editor command: Tlibtrace 'tcomment', a:beg, a:end, 
> a:comment_mode, ft|
|Do you have an older version of tlib installed?


|

**Comment by danielb2** [comment]
I did indeed. Thanks.

**Comment by danielb2** [comment]
btw, is there any way to get this to spit out a more useful message? Maybe check compatible tlib version and let the user know?

**Comment by danielb2** [comment]
:+1:
