### ISSUE TITLE
How to prevent 'O' from adding a comment

### ISSUE THREAD

**Issue by carlesandres** [tomtom/tcomment_vim#169]
I feel somewhat guilty for not figuring out by myself, but I'd like to prevent hitting `O` (capital `o`) on a commented line from making the new line a commented line.

**Comment by tomtom** [comment]
> but I'd like to prevent hitting |O| (capital |o|) on a commented line 
> from making the new line a commented line.
>
Are you asking for o, O to behave like <cr> (in insert mode)? If so, I 
cannot help you. You might want to ask the question on stackoverflow.

**Comment by carlesandres** [comment]
No, sorry for not making it clear. What I mean is that when I hit `O` in normal mode on a line which is already a comment, I want a new line to be created on top of it (usual VIM behaviour) but I do **not** want it to be commented by `tcomment`.

**Comment by tomtom** [comment]
> What I mean is that when I hit |O| in normal mode on a line which is 
> already a comment, I want a new line to be created on top of it (usual 
> VIM behaviour) but I do *not* want it to be commented by |tcomment|.
>

See :help fo-table, especially the "o" value for &formatoptions.

Regards

**Comment by carlesandres** [comment]
Awesome! Thanks for the help. I have managed to set it up as desired by adding:
```
:set formatoptions-=o
```
to my `.vimrc`. It never occurred to me that that was a VIM setting and not `tcomment`. 😅
