### ISSUE TITLE
Help request for oddball file type

### ISSUE THREAD

**Issue by ghoetker** [tomtom/tcomment_vim#178]
More of a help request than issue, but hoping for some assistance.  I am working with a filetype unknown to tcomment, .cypher.  The desired style for commenting is 

    // A single line comment
    // Actually, that's it. No separate block commenting desired.

For the life of me, I can't figure out the proper incantations, er, configurations to achieve this.  I'm relatively new to vim, so probably overlooking the obvious.

Thanks for the wonderful plugin!!

**Comment by tomtom** [comment]
Does

     call tcomment#DefineType('cypher', '// %s')

work for you?

If not, what is the filetype? (:echo &ft)

Regards

**Comment by ghoetker** [comment]
Thank you for the quick answer. Indeed, that was the required magic.  I appreciate your help with what I'm sure was a pretty basic question.
