### ISSUE TITLE
Insert comment symbols in the beginning of the line (vim)

### ISSUE THREAD

**Issue by whitecolor** [tomtom/tcomment_vim#182]
Say I have vim script with an indent of two spaces:
```
  call dein#add...
  call dein#add...
```

If I comment selected lines in (visual mode) using `<c-_><c-_>`, I get:
```
  " call dein#add...
  " call dein#add...
```

How is it possible to get comment symbols being inserted at the beginning of the line?
```
"  call dein#add...
"  call dein#add...
```

**Comment by tomtom** [comment]
> How is it possible to get comment symbols being inserted at the
> beginning of the line?
>
> |" call dein#add... " call dein#add... |

Does col=1 help (see :h g:tcommentOptions and :h tcomment#Comment()).

**Comment by whitecolor** [comment]
Yes this works, thanks.
