### ISSUE TITLE
JSX block comment is <!-- --> instead of {/* */}

### ISSUE THREAD

**Issue by ApolloTang** [tomtom/tcomment_vim#186]
While block commenting JSX syntax, instead of using {/* */} like:

```
const App = () => (
  <div>
      {/*
          <AddTodo />
          <VisibleTodoList />
      */}
    <Footer />
  </div>
)
```

<C-_>b is placing HTML comment syntax  like:

```
const App = () => (
  <div>
    <!-- <AddTodo /> -->
    <!-- <VisibleTodoList /> -->
    <Footer />
  </div>
)
```

I am not sure if this is a bug or I am missing some configuration.

please help!

Thank you!

**Comment by ApolloTang** [comment]
Works now after updated to newer version of tcomment !

**Comment by ApolloTang** [comment]
`echom &ft synIDattr(synID(line("."), col("."), 1), "name")`
at the cursor location give: `javascript.jsx xmlTag`
![screen shot 2019-01-30 at 2 32 18 am](https://user-images.githubusercontent.com/1150961/51965359-4b802000-2437-11e9-86d3-7a59a4b95b0a.png)

**Comment by ApolloTang** [comment]
In the following situation it is incorrectly apply the block comment
When expected the line comment ('//') inserting to the beginning of line:

<img width="666" alt="screen shot 2019-01-30 at 9 46 21 am" src="https://user-images.githubusercontent.com/1150961/51988942-f282ad00-2473-11e9-803f-8982ec7d4eee.png">

**Comment by tomtom** [comment]
Does it help to set

    let g:tcomment#filetype#guess_javascript = 1

**Comment by ApolloTang** [comment]
does not help :( 

![screen shot 2019-01-31 at 12 51 25 am](https://user-images.githubusercontent.com/1150961/52033276-6c597b80-24f2-11e9-82fa-6917ab398142.png)

Thanks for looking into this.

**Comment by ApolloTang** [comment]
![screen shot 2019-01-31 at 2 30 15 am](https://user-images.githubusercontent.com/1150961/52038528-a598e800-2500-11e9-95a2-4b295ca1fa87.png)

I notice something: the line where it is "javascript.jsx jsxRegion", it also lost syntax highlight.
I think this might be something to do with region detection ??

**Comment by tomtom** [comment]
Could you please check the syntax name at the position in question.

**Comment by tomtom** [comment]
Please see `:h tcomment-debug` or the hopefully helpful instructions at https://github.com/tomtom/tcomment_vim for how to collect the necessary data/logs (`:call tcomment#DebugInfo()`) that could help resolving this issue.

**Comment by ApolloTang** [comment]
![screen shot 2019-01-31 at 11 35 10 am](https://user-images.githubusercontent.com/1150961/52069230-55477780-254c-11e9-855d-68583debb61e.png)

**Comment by ApolloTang** [comment]
I got :

![screen shot 2019-01-31 at 11 34 45 am](https://user-images.githubusercontent.com/1150961/52069327-82942580-254c-11e9-8ae9-a184bc2e29bb.png)

when `:Tlibtraceset --file=tcomment.log +tcomment`

**Comment by ApolloTang** [comment]
my guess is `stx = xmlTag` is the culprit ?

**Comment by ApolloTang** [comment]
![screen shot 2019-01-31 at 11 41 20 am](https://user-images.githubusercontent.com/1150961/52069660-31d0fc80-254d-11e9-94f8-ffdd7bb0020a.png)

**Comment by ApolloTang** [comment]
![screen shot 2019-01-31 at 11 42 45 am](https://user-images.githubusercontent.com/1150961/52069749-5dec7d80-254d-11e9-9d3d-aee79f080312.png)

**Comment by tomtom** [comment]
Does this help?

    let g:tcomment#filetype#syntax_map_user = {
                    \ 'xmlTag': {
                    \     'filetype': {
                    \         'javascript.jsx': 'jsx',
                    \     },
                    \ }
                    \ }

**Comment by ApolloTang** [comment]
Thanks

**Comment by ApolloTang** [comment]
@tomtom you  are correct, the syntax definition is the problem: 

I am switching to  [https://github.com/neoclide/vim-jsx-improve](https://github.com/neoclide/vim-jsx-improve) which work:

![screen shot 2019-02-01 at 10 49 22 am](https://user-images.githubusercontent.com/1150961/52133506-7755fe00-260f-11e9-8f6e-ae75672e3b93.png)

Here is the screenshot for using tcomment with jsx after the switch:
![screen shot 2019-02-01 at 10 49 06 am](https://user-images.githubusercontent.com/1150961/52133520-7d4bdf00-260f-11e9-8ac0-437425fe105b.png)
