### ISSUE TITLE
can't comment on markdown files

### ISSUE THREAD

**Issue by rpietro** [tomtom/tcomment_vim#189]
Have been trying to comment markdown files without success, the comment invariably comes out as '>'. Here is what I've tried:

1. renaming the files as .markdown, .mdown, .md
2. setting syntax as markdown
3. setting syntax as html

every single time I get the following msg: 

      :'<,'>TCommentMaybeInline  

I am clearly doing something wrong. Any thoughts?

**Comment by tomtom** [comment]
> the comment invariably comes out as '>'

Which version of tcomment (:echo g:loaded_tcomment) do you use? Which 
markdown mode do you use? What's the value of &comments and &commentstring?

Regards

**Comment by rpietro** [comment]
@tomtom thanks for getting back to me so quickly. my best shot at your questions:

tcomment_vim is version 3.07

is markdown mode the markdown plugin that will determine the commentstring? if so, I'm using https://github.com/plasticboy/vim-markdown . btw, I tried to use  ` let g:vim_markdown_no_default_key_mappings = 1` on .vimrc to avoid a key mapping conflict with tcomment_vim as I thought that in some way I was issuing a comment bloc command in vim-markdown , but that didn't work

as for the value of value of &comments and &commentstring, is this instantiated through vim-markdown? I'm not sure how to get its value.

**Comment by tomtom** [comment]
Based on the information you gave me I cannot tell what could be the problem. Could you please try

  :set verbosefile=tcomment.log
  20verbose :TCommentMaybeInline

and send me the resulting log file. Please also send me an example input file and the exact key sequences you type. Thanks.

You might also try to update the tcomment plugin first. After updating, you could also install the tlib plugin and then type `:Tlibtraceset --file=tcomment.log +tcomment` to get a more concise log.

**Comment by rpietro** [comment]
sorry for the delay, got caught up with a ton of work. the log is at https://gist.github.com/rpietro/c70a722f43686ad5e280e3130e190c9b

I tried to make it concise, but am probably doing something wrong. I really appreciate your help

**Comment by tomtom** [comment]
I think the problem simply is that version 3.07 didn't have a custom definition for markdown yet. This was introduced in 3.08, which got lost somehow. I now uploaded a new version. Please update.
