### ISSUE TITLE
E117: Unknown function: strwidth

### ISSUE THREAD

**Issue by bilougit** [tomtom/tcomment_vim#190]
Hi, I just installed this plugin to use it into my `.vue` files containing html like code.

When I type `gc{motion}` or `gcc` nothing happens to my code except an error shows up:

> Error detected while processing function TCommentOpFunc_gcc..tcomment#OperatorLine..tcomment#Operator..tcomment#Comment..<SNR>94_GetCommentDefinition..<SNR>94_GuessFileType:
> line   35:
> E117: Unknown function: strwidth

**Comment by tomtom** [comment]
>     E117: Unknown function: strwidth

Do you use an ancient version of vim?
