### ISSUE TITLE
non-indented hashtag in Python scripts

### ISSUE THREAD

**Issue by victoriastuart** [tomtom/tcomment_vim#195]
Hi - great plugin!!  This may be Neovim (Nvim)-related, as I just tried it in Vim, and there it seemed to not be an issue.

In indented Python code (in Nvim), when I open a new line (O, o, or entering Insert mode) and type the hashtag (#), that hashtag moves to column position 1 (non-indented).  I have to manually move to the start of the line, and properly indent those commented lines.

**Comment by tomtom** [comment]
> In indented Python code (in Nvim), when I open a new line (O, o, or
 > entering Insert mode) and type the hashtag (#), that hashtag moves to
 > column position 1 (non-indented).

Unless you used tcomment to insert the comment prefix, this isn't caused 
by tcomment. You might want to ask a vim user who writes python.

**Comment by victoriastuart** [comment]
Hi: sorry, this was my fault.  It turns out I had "set smartindent" in my ~/.vimrc.  My "issue" / solution is discussed here, http://vim.wikia.com/wiki/Restoring_indent_after_typing_hash

Basically, replace

    set smartindent
with

    set cindent
    set cinkeys-=0#
    set indentkeys-=0#
in .vimrc

My apologies!  :-)
