### ISSUE TITLE
hyphen converts to &#45;  in html files

### ISSUE THREAD

**Issue by skylite21** [tomtom/tcomment_vim#196]
from this:
`<nav class="main-menu">`

I get this:
`<!-- <nav class="main&#45;menu"> -->`
Is there a way to turn this off? I would need just regular hyphens. 
Im on vim8.0

**Comment by tomtom** [comment]
> I get this:
> ||
> Is there a way to turn this off? I would need just regular hyphens.

You could define g:tcomment#replacements_xml before loading the plugin 
(e.g. in .vimrc) so that hyphens don't get replaced. This could cause 
problems with nested comments though.

HTH
