### ISSUE TITLE
Embedded R code in Rmarkdown (.Rmd) files

### ISSUE THREAD

**Issue by mmclaren42** [tomtom/tcomment_vim#197]
I am using the vim-rmarkdown plugin (https://github.com/vim-pandoc/vim-rmarkdown) to edit Rmarkdown documents, which consist of markdown text with blocks of R code (as described here http://rmarkdown.rstudio.com/authoring_rcodechunks.html). The vim-rmarkdown plugin handles the recognition of the code chucks in documents with ft=rmd as R code for syntax highlighting purposes, but tcomment seems to treat text in and outside of the code blocks as markdown. Would be very useful if tcomment could detect when inside an R code block as well, to use R style commenting within the code blocks. I don't yet understand how tcomment handles embedded code, so sorry if I missed something, and thanks for your useful plugin!

**Comment by tomtom** [comment]
> In Rmarkdown documents, tcomment seems to be treating lines in blocks of 
> R code (delimited as described here 
> http://rmarkdown.rstudio.com/authoring_rcodechunks.html)

Could you please possition the cursor at the embedded R code end run:

     :echo synIDattr(synID(line("."), col("."), 1), "name")

Could you please also report

     :echo &ft

Thanks

**Comment by mmclaren42** [comment]
Running `:echo synIDattr(synID(line("."), col("."), 1), "name")` on the lines beginning with backticks that denote the start or end of a code block returns "rmdRChunkDelim" (inside a code block,  the result depends on the text under the cursor).

Running ":echo &ft" returns "rmd".

**Comment by tomtom** [comment]
> inside a code block, the result depends 
> on the text under the cursor

That would be the interesting part though. Do the styles have "r" as 
common prefix?

**Comment by mmclaren42** [comment]
Hmm. I was hoping tcomment perhaps recognized the code blocks by the lines delimiting their boundaries, because the styles do not have a consistent format, and do not even always start with "r". For example, consider this code block:
````
```{r package_options, include=FALSE}
library(ggplot2)
# knitr options
knitr::opts_knit$set(progress=TRUE, verbose=TRUE)
# Do some R stuff
1:10**2
```
````
Running the command `:echo synIDattr(synID(line("."), col("."), 1), "name")` on the first character of each line returns
1. rmdRChunkDelim
2. rPreProc
3. rComment
4. rmdRChunk
5. rComment
6. rNumber
7. rmdRChunkDelim
which looks promising. But if cursor is over a "(" or ")", the the style is simply "Delimiter".

**Comment by mmclaren42** [comment]
Note, the implemented fix seems to have changed the behavior from always using markdown style comments to always using R style comments when ft=rmd, both inside and outside the R code blocks. To me at least, this is preferable to the former behavior, but I'm guessing is not the intended behavior for files with embedded code.

From what I can tell so far, if R comments were used whenever the style starts with 'r' and also on the style 'Delimiter' (which seems like it should be 'rDelimiter'...perhaps a bug in the rmarkdown plugin), and markdown-style commenting was used everywhere where the style is blank or doesn't start with 'r', then the desired behavior of R comments inside and markdown comments outside of code blocks would hold.
