### ISSUE TITLE
space

### ISSUE THREAD

**Issue by squm** [tomtom/tcomment_vim#199]
`:let g:tcommentOptions = {'col': 1}<CR>`

adds space character between comment string ‘//’ and tab indentation character

**Comment by tomtom** [comment]
> adds space character between comment string ‘//’ and tab indentation 
> character

Try to add:

let g:tcommentOptions = {'whitespace': 'no', ...}

Please see `:h tcomment#Comment()`.

**Comment by squm** [comment]
```
map [ot :let g:tcommentOptions = { 'col': 1, 'whitespace' : 'no' }<CR>
map ]ot :let g:tcommentOptions = {}<CR>
```

looks allright
