### ISSUE TITLE
Comment inside php when code is inline

### ISSUE THREAD

**Issue by luffah** [tomtom/tcomment_vim#203]
Hello,
if i use tcomment on a php line like that
```php
<?php include(dirname(__FILE__).'/header.php'); ?>
``` 
then i obtain
```
// <?php include(dirname(__FILE__).'/header.php'); ?>
```
which is not really something PHP will interpret as comment.

Personally, i prefer to obtain
```
<?php // include(dirname(__FILE__).'/header.php'); ?>
```
or
```
<?php /* include(dirname(__FILE__).'/header.php'); */ ?>
```

Thank you for your work.
------------------------------------------------------------------
As a workaround. I have this on my own vim config. 
```vim
" Note : I could use :call tcomment#Comment(...) but i prefer to interface the plugin which comment
command! -range -bar Comment
      \ if &ft=='php'
      \ | silent! call s:_PHP_inline_toggle_comment()
      \ | else  | silent! exe 'TComment' | endif

fu! s:_PHP_inline_toggle_comment()
  let l:comment_str=escape(&commentstring,'*\/')
  let l:php_begin=''
  let l:php_end=''
  let l:l=getline('.')
  if (l:l =~ '<?php.*?>')
    let l:php_begin='<?php '
    let l:php_end=' ?>'
  elseif (l:l =~ '<.*>$')
    let l:comment_str='<!--%s-->'
  endif
  let l:pattern_is_commented=printf('%s\s*%s\s*%s'
        \, l:php_begin
        \, substitute(l:comment_str,'%s','\\(.*\\)','')
        \, l:php_end
        \)
  let l:is_commented=(match(l:l,l:pattern_is_commented) > -1)
  if l:is_commented
    " uncomment
    let l:command_comment=printf('s/%s/%s\1%s/'
          \, l:pattern_is_commented
          \, l:php_begin, l:php_end
          \)
  else
    " comment
    let l:command_comment=printf('s/%s\(.*\)%s/%s%s%s/'
          \, l:php_begin, l:php_end
          \, l:php_begin
          \, substitute(l:comment_str,'%s','\\1','')
          \, l:php_end
          \)
  endif
  exe ':silent! '.l:command_comment
endfu
```
I tried to integrate this solution in TComment, but i had some difficulty to well understand the code  since i'm used to write code in project with this kind of directory structure.
```vim
autoload/tcomment.vim "globals things
autoload/tcomment/filetype.vim
autoload/tcomment/completion.vim
...
```

**Comment by tomtom** [comment]
> if i use tcomment on a php line like that
> 
> <?php include(dirname(__FILE__).'/header.php'); ?>
> 
> then i obtain
> 
> |// <?php include(dirname(__FILE__).'/header.php'); ?> |
> 
> which is not really something PHP will interpret as comment.

You can use inline-comments if you really want to. Anyway, I'd suggest 
to rewrite this as

     <?php
     include(dirname(__FILE__).'/header.php');
     ?>

Embrace the newline.

Other than that, I won't support something like that.

BTW one could argue, tcomment should actually use  in this 
case anyway, since the line is probably part of something that would 
normally be interpreted as HTML or similar.

> I tried to integrate this solution in TComment, but i had some 
> difficulty to well understand the code since i'm used to write code in 
> project with this kind of directory structure.
> 
> autoload/tcomment.vim"globals things
> autoload/tcomment/filetype.vim
> autoload/tcomment/completion.vim

I tend to agree to some extent. tcomment's source code is old and 
predates the autoload feature. Feel free to refactor the code according 
to the proposed structure -- without introducing new bugs and without 
breaking other plugins that might make direct use of some exposed 
function/variable. I personally don't have the time for this.

**Comment by luffah** [comment]
(additionnal informations)
I agree to make clean blocks.
The reason I use this particular setting, is for testing template.
The typical case is ( for some cms like Drupal7 ): 
```php
 <div class="<?php  context_classes(); ?>">
 </div>
```
Formatting it with newlines give :
```php
 <div class="<?php
       echo context_classes();
  ?>">
 </div>
```
Well, i don't know it can be a clean way to do it too. (especially, if i have multiple values like that)

About doing HTML comments around PHP statement for disabling a function call, i think it is an error in terms of performance and stability of the code.
