### ISSUE TITLE
change commentstring in css files

### ISSUE THREAD

**Issue by vasyapupkin123456** [tomtom/tcomment_vim#204]
How to change from commentstring=/*%s*/ to commentstring=//\ %s ?
If I write it in ~/.vim/after/ftplugin/css.vim

`setlocal commentstring=//\ %s`
or 
`set commentstring=//\ %s`
, tcomment ignore this option and comment like:

/* ewewfwe */

**Comment by tomtom** [comment]
> How to change from commentstring=//%s// to commentstring=//\ %s ?
> If I change it in ~/.vim/after/ftplugin/css.vim, tcomment ignore this 
> option and comment like:

Put the following into your vimrc file:

     call tcomment#DefineType('css', '// %s')

The cms option is ignored because a custom comment style is defined by 
default in autoload/tcomment.vim.

**Comment by vasyapupkin123456** [comment]
Thanks! Resolved.
