### ISSUE TITLE
mstmprc comment string

### ISSUE THREAD

**Issue by Konfekt** [tomtom/tcomment_vim#206]
In `~/.mstmprc`, there is the

```vim
  commentstring=:// %s
	Last set from ~/.config/.vim/plugged/tcomment_vim/autoload/tcomment.vim
```

However, the right one seems to be `commentstring=# %s`.

**Comment by tomtom** [comment]
Could you please check this again with tcomment disabled. Thanks. tcomment shouldn't permanently set an option. It's possible though that is sets an option temporarily.

**Comment by Konfekt** [comment]
Without `tcomment.vim`, `verbose set commentstring?` gives
```vim
commentstring=:// %s
```
So it seems to be preset.

**Comment by tomtom** [comment]
> So it seems to be preset.

You could try to set b:tcomment_def_{FILETYPE} to {'commentstring': 
'whatever you want %s'}.

**Comment by Konfekt** [comment]
Yes, I close this issue as it seems that Vim simply does not set the commentstring appropriately, even though there is a file type and syntax highlighting defined.
