### ISSUE TITLE
Latest build fails to toggle current line in Neovim

### ISSUE THREAD

**Issue by cujomalainey** [tomtom/tcomment_vim#209]
![image](https://user-images.githubusercontent.com/1537150/37997063-0da80228-31d7-11e8-8462-5e91d2d84b2a.png)

This was achieved by simply typing `gcc` in normal mode. Visual toggle works fine. Not sure what is crashing.

Vim config is [here](https://github.com/cujomalainey/system-config/blob/master/init.vim).

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
```

**Comment by tomtom** [comment]
> This was achieved by simply typing |gcc| in normal mode. Visual toggle 
> works fine. Not sure what is crashing.

Are you sure you didn't define some custom map somewhere?

If so, please make sure you have the latest version from github. There 
were some changes. E.g. tcomment#OperatorLine() was renamed to 
tcomment#operator#Line().

**Comment by tomtom** [comment]
`:verbose map gcc` could help.

**Comment by cujomalainey** [comment]
It was upon doing a `PlugUpdate` that `gcc` broke. I didn't change my config between the update and when `gcc` broke. Here is the output of the above command.

![image](https://user-images.githubusercontent.com/1537150/38043204-adb86cde-3273-11e8-8c70-87ffdeafbfe4.png)

**Comment by cujomalainey** [comment]
Apparently I forgot to restart vim after the upgrade. Restarting it fixed the problem.
