### ISSUE TITLE
start-up time after refactoring

### ISSUE THREAD

**Issue by Konfekt** [tomtom/tcomment_vim#210]
After the latest refactoring, start-up time has risen, `vim-profiler.py` gives
```
1	 63.430   tcomment_vim
8	  5.132   vim-fugitive
```
Is this intended?

**Comment by tomtom** [comment]
> |1 63.430 tcomment_vim 8 5.132 vim-fugitive |

This could be a consequence of the call to tcomment#deprecated#Check() 
in plugin/tcomment.vim. Could you rerun the test with that call removed? 
If this is the cause, I'll put it somewhere else.

Regards

**Comment by Konfekt** [comment]
Yes, now fugitive and t-comment traded places
```vim
5	  8.365   vim-fugitive
6	  7.794   tcomment_vim
```

**Comment by Konfekt** [comment]
I don't know how to open this issue again, but it seems that

https://github.com/tomtom/tcomment_vim/commit/404fddbff2b9d5d8e66eb7cc29d5109630adab3c

bumped up the start-up time considerably again.

**Comment by tomtom** [comment]
So you cannot verify the times stated in https://github.com/tomtom/tcomment_vim/pull/217 ?

How did the startup time change for you?

**Comment by Konfekt** [comment]
Vim-profiler.py gives, for example,
```
3	 20.586   tcomment_vim
8	  4.777   delimitMate
```
Before, see above comment, it was,
```
  7.794   tcomment_vim
```

**Comment by Konfekt** [comment]
Yeah, it's back to old speed:
```
5	  8.116   delimitMate
6	  7.362   tcomment_vim
```
