### ISSUE TITLE
tcomment don't recognize embedded syntax anymore?

### ISSUE THREAD

**Issue by zdm** [tomtom/tcomment_vim#214]
Hi.
I have perl file with embedded C++ code blocks, that are highlited properly, as C++ code.
But tcomment comments this blocks as perl code.
At the past, I remember, that tcomment commented such blocks, using c++ comments.
I tried to execute
```
:echo synIDattr(synID(line("."), col("."), 1), "name")
```
and it shows, that this is C++ code.

I am using latest vim and tcomment.

**Comment by tomtom** [comment]
Could you please post a minimal example an tell me which plugins are involved (in case you don't use the standard ftplugins/syntax files that come with vim). Please let me also know which version of vim, tcomment (`:echo g:loaded_tcomment`) you use.

**Comment by tomtom** [comment]
I'd assume you have to do `let tcomment#filetype#guess_perl = 1` in order to make it work.

**Comment by zdm** [comment]
I updated my vimrc, using your suggestions.
Thank you.
