### ISSUE TITLE
Fail to toggle, if no <space> after the comment sign

### ISSUE THREAD

**Issue by seaspeak** [tomtom/tcomment_vim#227]
If you enter visual mode to select two lines, and put `gcc`, it yields a incorrect result.

filetype: vim

# Fail

    "Plug 'tomtom/tcomment_vim
    Plug 'tomtom/tcomment_vim

becomes

    " "Plug 'tomtom/tcomment_vim
    " Plug 'tomtom/tcomment_vim

# Successful:

    "Plug
    "Plug

or

    Plug
    Plug

or

    " Plug
    " Plug

**Comment by tomtom** [comment]
>   Fail
> 
> |"Plug 'tomtom/tcomment_vim Plug 'tomtom/tcomment_vim |
> 
> becomes
> 
> |" "Plug 'tomtom/tcomment_vim " Plug 'tomtom/tcomment_vim |

Why do you consider this a fail. This is the expected outcome -- see `:h 
tcomment`. Maybe I didn't understand your report.

**Comment by seaspeak** [comment]
The first line `"Plug 'tomtom/tcomment_vim` is commented. The second isn't. The result is both of them are commented. The first line is commented twice.

**Comment by seaspeak** [comment]
If this is as expected, than please close the issue. Thinking this through, it is a not bad behavior for me.
