### ISSUE TITLE
Julia support?

### ISSUE THREAD

**Issue by sbromberger** [tomtom/tcomment_vim#241]
Right now, tcomment blocks comments in `.jl` files with `#= ... =#`. The correct commenting format is simply `# ` at the beginning. Is there a straightforward way to set this?

**Comment by tomtom** [comment]
The Julia ftplugin isn't distributed with vim, is it?

Isn't `#= ... =#` for block comments and `#` for line comments correct? (According to https://docs.julialang.org/en/v0.6.1/stdlib/punctuation/) But maybe I misunderstand your issue.

**Comment by sbromberger** [comment]
> The Julia ftplugin isn't distributed with vim, is it?

No, I don't think so.

> Isn't `#= ... =#` for block comments and `#` for line comments correct?

Yes, but selecting multiple lines and then `gcc` puts block comments on every line (not at the beginning and end of the selection). Therefore, `#` at the beginning of the line would be more appropriate (and is easier to undo manually since with the block comment you have to jump to the end of the line to remove the characters).

**Comment by tomtom** [comment]
This should be fixed by now, isn't it?

**Comment by sbromberger** [comment]
It's fixed! Thank you so much.
