### ISSUE TITLE
tcomment#type#Define broken

### ISSUE THREAD

**Issue by Grueslayer** [tomtom/tcomment_vim#245]
These three lines work like a charm in the past but stopped working with one of the last commits:

~~~vim
call tcomment#type#Define('clipper',             '// %s')
call tcomment#type#Define('clipper_block',       "/*%s */\n * ")
call tcomment#type#Define('clipper_inline',      "/* %s */")      
~~~

They still meet the documentation and I don't see why they affect the lines mentioned in the error:

~~~
Error detected while processing C:\Users\jst\vimfiles\bundle\tcomment_vim\autoload\tcomment\types\default.vim:
line  222:
E116: Invalid arguments for function tcomment#type#Define
~~~

**Comment by boutell** [comment]
+1:

```
Error detected while processing /home/tom/.vim/plugged/tcomment_vim/autoload/tcomment/types/default.v
im:
line  222:
E116: Invalid arguments for function tcomment#type#Define
```

I'm trying to comment something out in a .vue file.

The weirdest part is that it does comment the stuff out... and it works fine after the first use in a given launch of vim.

Thanks for your work on this module! It is appreciated.

**Comment by bugeats** [comment]
Broken here on Neovim v0.3.4. Same error as above.

**Comment by boutell** [comment]
Confirmed: everything is perfect forever. Thank you!
