### ISSUE TITLE
dashes replaced with &#45; in comments

### ISSUE THREAD

**Issue by victoriastuart** [tomtom/tcomment_vim#253]
Wonderful plugin, but in HTML files dashes are being replaced by HTML codes in commented text:

```
http://js.cytoscape.org/#getting started
<!-- http://js.cytoscape.org/#getting&#45;started -->
```

Is there a solution to this?  Thanks!

**Comment by victoriastuart** [comment]
Wonderful plugin, but in HTML files dashes are being replaced by HTML codes in commented text:

```
http://js.cytoscape.org/#getting started
<!-- http://js.cytoscape.org/#getting&#45;started -->
```

Is there a solution to this?  Thanks!

**Comment by victoriastuart** [comment]
OK, I "solved" this.

1. Find the problem

```
[victoria@victoria tcomment_vim]$ pwd; rg . -e '&#45;'

    /home/victoria/.vim/bundle/tcomment_vim
    ./autoload/tcomment.vim
    152:                "\     '-': '&#45;',
```

2. Edit `~/.vim/bundle/tcomment_vim/autoload/tcomment.vim` (line 152 per ripgrep result, above):

```
                "\     '-': '&#45;',
                "\     '&': '&#38;',
                \     '-': '-',
                \     '&': '&',
```

The simplest solution is to simply replace `-` with `-` ...

3. Restart Vim.

---

![Selection_999(2459)](https://user-images.githubusercontent.com/2575920/63132631-b11c9f80-bf76-11e9-93ac-67882f6d5212.png)

**Comment by tomtom** [comment]
If you don't want the replacements, set the variable to an empty dictionary. IIRC this could cause problems with nested comments (e.g, in embedded docs), which is why this feature exists in the first place.
