### ISSUE TITLE
[question] how to comment using shortcut like on videos?

### ISSUE THREAD

**Issue by mandaputtra** [tomtom/tcomment_vim#268]
I'm sorry, I'm noob in vim but how to comment with these plugins? Here the debug info and some videos.

```
TCOMMENT: &ft = javascript => javascript
TCOMMENT: stx = jsString => javascriptString
TCOMMENT: ct  = {'rxmid': '', 'rxend': '', 'commentstring': '// %s', 'commentstring_rx': '\%%(// %s\|/* %s */\)', 'mode': '', 'filetype': 'javascript', 'replacements': {'*/': {'subst': '|)}>#', 'guard_rx': '^\s*/\?\*'}, '/*': {'subst': '#<{(|', 'guard_rx': '^\s*/\?\*'}}, 'rxbeg': '\*\+'}
```

Videos showing use of `gcc` [on insert mode](https://streamable.com/rs22jj).

But if I use, `:TComment` on the `vim-command-terminal` it works like charm. Only the shortcut, I can't use it. 

And the last one, what is {motion} ?

Thanks for your time and sorry for the question.

**Comment by mandaputtra** [comment]
Sorry I just ask on the [vi.stackexchange.com](https://vi.stackexchange.com/questions/25492/how-to-acctually-comment-with-tcomment-vim) for better discussion related to question.

**Comment by tomtom** [comment]
gcc doesn't work in insert mode. You can use <c-_><c-_> (|g:tcomment_mapleader1| twice) in insert mode instead.
