### ISSUE TITLE
Disable blockwise comment?

### ISSUE THREAD

**Issue by semin-park** [tomtom/tcomment_vim#269]
Thank you for this great feature!

I have a quick question about how to disable blockwise comments.

All C/C++ codes are using linewise comments (`//`), but for some reason, `.cu` and `.cuh` files (CUDA files) are commented using blockwise comments (`/* ... */`).

How would I be able to disable this behaviour and force to use linewise (`//`) comment for CUDA files as well?

**Comment by tomtom** [comment]
Put this into autoload/tcomment/types/semin-park.vim:

    call tcomment#DefineType('cuda', tcomment#GetLineC('// %s'))

If this works for you, I'll add it to the default definitions.

**Comment by semin-park** [comment]
That worked like a charm! It seems like `DefineType` is now deprecated so I changed it to `#type#Define`, but anyway it works fine :)
