### ISSUE TITLE
[feature request] support rust doc comment

### ISSUE THREAD

**Issue by GopherJ** [tomtom/tcomment_vim#282]
![Peek 2021-02-08 09-28](https://user-images.githubusercontent.com/33961674/107166150-11679280-69f0-11eb-84e3-e501513f3290.gif)

Hi, is it possible to support rust's doc comment? Sometimes I need to use the example code in doc comment

**Comment by tomtom** [comment]
You would have to provide further details. I don't use rust.

**Comment by GopherJ** [comment]
There isn't any details other than `///`
