### ISSUE TITLE
Issue commenting HTML with PHP inside. Minus character becomes "&#45;"

### ISSUE THREAD

**Issue by D3faIt** [tomtom/tcomment_vim#288]
I have an issue with this code:

    <p title="Total XP: <?php echo $submittedXP ?>">XP: <?php echo ($submittedXP - $submittedrankinfo['required_xp']); ?></p>

When commented out, it looks like this:

    

The `-` symbol, becomes `&#45;` and breaks the code.

---

**Expected result**
either:

    

or

**Comment by tomtom** [comment]
Does the above commit solve your problem?
