### ISSUE TITLE
Disable default mappings

### ISSUE THREAD

**Issue by luiz00martins** [tomtom/tcomment_vim#292]
It would be nice if there was an option to disable the default mappings, so they wouldn't clobber any other mappings the user may have set to the same keys (since plugins are loaded after your `vimrc`, the plugin will overwrite your `vimrc` mappings).

*Note: I'm not sure if this feature is already in place. If it is, I wasn't able to find it in the README or docs.*

**Comment by tomtom** [comment]
Does `:h g:tcomment_maps` help?

**Comment by luiz00martins** [comment]
Yes, that's it! Thank you.
