### ISSUE TITLE
How to force # instead of >

### ISSUE THREAD

**Issue by OilSubjectLoss7** [tomtom/tcomment_vim#298]
txt file seems to comment with ">" instead of "#". How do i fix this?

**Comment by tomtom** [comment]
> txt file seems to comment with ">" instead of "#". How do i fix this?

Did you set any filetype? If not, tcomment uses the information from 
&comments or &commentstring.

BTW I personally edit txt files with filetype=markdown.

**Comment by OilSubjectLoss7** [comment]
> txt file seems to comment with ">" instead of "#". How do i fix this?
> Did you set any filetype? If not, tcomment uses the information from &comments or &commentstring. BTW I personally edit txt files with filetype=markdown.

I don't really get how  it works

Like this?

`g:tcomment_opleader1 "# "`
Or
`let g:tcomment_opleader1 "# "`
Or
`g:tcomment_opleader1 = "# "`
Or
`let g:tcomment_opleader1 = "# "`

They don't work at all

**Comment by OilSubjectLoss7** [comment]
> txt file seems to comment with ">" instead of "#". How do i fix this?
> Did you set any filetype? If not, tcomment uses the information from &comments or &commentstring. BTW I personally edit txt files with filetype=markdown.

I tried the md filetype and it's even worse



The command i'm applying it too can read it now. But that's not what i'm after for. How do i make the comment to yhis "#" instead of this ">" or ""

**Comment by OilSubjectLoss7** [comment]
Fuck it. I'm going back to commentary

**Comment by tomtom** [comment]
Yes, please.

**Comment by OilSubjectLoss7** [comment]
Sorry for the rude outburst, i figured it out. Thanks. Nice plugin btw.
