### ISSUE TITLE
`<c-_><c-_>` does not work, but `gcc` works well

### ISSUE THREAD

**Issue by dantezhu** [tomtom/tcomment_vim#299]
When I type `Ctrl -`, it just works like I type `-`, the cursor move back.
I am using gVim, version 8.2.5136, but other version does not work too.
![image](https://user-images.githubusercontent.com/1105212/174626079-9202cc57-12b3-4a3d-8cba-9d82b42a28dc.png)

I am using the lastest version of tcomment.

**Comment by dantezhu** [comment]
it seems like, in gvim, when I type `Ctrl -`, it will trigger `Ctrl -`, not `Ctrl _`.

but when I use macvim, it will trigger `Ctrl _`.

it is very strange behavior

**Comment by dantezhu** [comment]
seems like it is gvim's bug. I have raise a [issue](https://github.com/vim/vim-win32-installer/issues/270) to gvim.

**Comment by tomtom** [comment]
I think this is documented somewhere. VIM assumes the US keyboard layout 
for certain tasks. I agree this is weird but I don't know of a work around.
