### ISSUE TITLE
How to make uncomment remove only 1 space?

### ISSUE THREAD

**Issue by huyz** [tomtom/tcomment_vim#303]
I have:
```vim
let g:tcomment#options = {
            \ 'col': 1,
            \ 'whitespace': 'no',
            \ 'strip_whitespace': '0'
            \ }
````

This works for adding no whitespace. But then when I reverse the commenting operation, a space gets eaten. How do I stop whitespace from being eaten?

**Comment by tomtom** [comment]
Which filetype is this about? It seems to me this is a problem with filetypes whose comment definition uses `commentstring_rx` since the whitespace option deals only with `commentstring`.

**Comment by huyz** [comment]
Oh this was for javascript and not languages like vimscript/python/shell.
But you obviously figured that out and I can confirm your commit fixed it.

Thanks!
