### ISSUE TITLE
Having hard time configuring for C single line comments

### ISSUE THREAD

**Issue by cyboflash** [tomtom/tcomment_vim#48]
I'm having hard time figuring out how I should configure this plugin to use comments for a single  C line, i.e // as opposed to /\* ... */ . The desire is to use block comments when more than one line is selected visually and a single line comment when a single line is selected visually or no line is selected at all. Is it possible to achieve this?

**Comment by nhooyr** [comment]
Can confirm that works for me.

Thanks @tomtom

**Comment by nhooyr** [comment]
Only thing you'll have to change is to use `tcomment#type#Define` instead of `tcomment#DefineType`

**Comment by nhooyr** [comment]
```viml
  function! s:setup_tcomment() abort
    call tcomment#type#Define("c", {
          \ "commentstring": "// %s",
          \ "replacements": g:tcomment#replacements_c,
          \ }
          \ )
  endfunction

  augroup plugins
    autocmd!
    autocmd VimEnter * call s:setup_tcomment()
  augroup END
```

Exert from my dotfiles.

**Comment by nhooyr** [comment]
Nvm just the following in my `init.vim` works.

```viml
  call tcomment#type#Define("c", {
        \ "commentstring": "// %s",
        \ "replacements": g:tcomment#replacements_c,
        \ }
        \ )
```

**Comment by tomtom** [comment]
The right place for this should be in `~/.vim/autoload/tcomment/types/my_defs.vim`. It might be necessary to add two additional argument:

    call tcomment#type#Define("c", {...DEF...}, {}, 1)

**Comment by nhooyr** [comment]
> The right place for this should be in ~/.vim/autoload/tcomment/types/my_defs.vim.

What's wrong with putting it in my `init.vim`/`.vimrc`?

The other arguments don't appear to be required.

**Comment by tomtom** [comment]
> What's wrong with putting it in my |init.vim|/|.vimrc|?

If you put it into vimrc, it always loads autoload/tcomment/type.vim at 
startup. If you follow my proposal, it should be loaded only when 
needed. So, there is nothing wrong with it, but it is not optimal.

> The other arguments don't appear to be required.

If you put it into vimrc, you don't need these arguments, because it is 
loaded before autoload/tcomment/types/default.vim. If it is not sure 
whether it gets loaded before default.vim, you should add these two 
arguments.

**Comment by nhooyr** [comment]
Awesome, that makes sense, thanks for clarifying!
